# Generated by Django 3.2 on 2021-05-01 13:58

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('original', models.ImageField(max_length=1000, null=True, upload_to='original/', verbose_name='Original image')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ImageSubSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField(default=0, help_text='Height of the current image in pixels', verbose_name='Height')),
                ('width', models.PositiveIntegerField(default=0, help_text='Width of the current image in pixels', verbose_name='Width')),
                ('apply', models.BooleanField(default=False, help_text='Apply uploaded watermark on image', verbose_name='Apply')),
                ('formats', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'DIB'), (2, 'JPEG'), (3, 'PNG'), (4, 'WEBP'), (5, 'BMP'), (6, 'EPS'), (7, 'SPIDER')], max_length=13, null=True, verbose_name='Formats images convert to')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='InnerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(max_length=1000, null=True, upload_to='original/', verbose_name='Original image')),
                ('marked', models.ImageField(blank=True, max_length=1000, null=True, upload_to='marked/', verbose_name='Marked image')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='django_image_field.image')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watermark', models.ImageField(blank=True, max_length=1000, null=True, upload_to='watermark/', verbose_name='Image to apply above other images')),
                ('settings', models.ManyToManyField(to='django_image_field.ImageSubSetting', verbose_name='Settings for all images in database')),
            ],
            options={
                'verbose_name': 'Image setting',
                'verbose_name_plural': 'Image settings',
            },
        ),
    ]
